name: twende_nalo
description: "A Flutter delivery app connecting customers, shop owners, and riders."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  google_fonts: ^6.2.1
  bounce: ^1.0.2
  motion: ^2.0.1
  flutter_spinkit: ^5.2.0

  # Navigation & Theming
  go_router: ^16.1.0
  adaptive_theme: ^3.6.0
  provider: ^6.1.2

  # Firebase Core
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

  # Utilities & Helpers
  uuid: ^4.4.0
  intl: ^0.20.2
  logger: ^1.0.0
  universal_io: ^2.2.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  http: ^1.1.0

  # Chat & Media
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^2.9.0
  image_picker: ^1.1.2
  share_plus: ^11.1.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/household_items.jpg
    - assets/images/electronics.jpg
    - assets/images/clothing.jpg
    - assets/images/food.jpg
    - assets/images/milk.jpg
    - assets/images/vegetables.jpg
    - assets/images/phone.jpg
    - assets/images/apples.jpg
