// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9bGVo2anM_IlLt9dIcw2XG291KD7dxcA',
    appId: '1:248749012948:android:74d137d0e509586a5a0841',
    messagingSenderId: '248749012948',
    projectId: 'twende-nalo',
    storageBucket: 'twende-nalo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9bGVo2anM_IlLt9dIcw2XG291KD7dxcA',
    appId: '1:248749012948:ios:74d137d0e509586a5a0841',
    messagingSenderId: '248749012948',
    projectId: 'twende-nalo',
    storageBucket: 'twende-nalo.firebasestorage.app',
    iosBundleId: 'com.example.twendeNalo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9bGVo2anM_IlLt9dIcw2XG291KD7dxcA',
    appId: '1:248749012948:ios:74d137d0e509586a5a0841',
    messagingSenderId: '248749012948',
    projectId: 'twende-nalo',
    storageBucket: 'twende-nalo.firebasestorage.app',
    iosBundleId: 'com.example.twendeNalo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9bGVo2anM_IlLt9dIcw2XG291KD7dxcA',
    appId: '1:248749012948:windows:74d137d0e509586a5a0841',
    messagingSenderId: '248749012948',
    projectId: 'twende-nalo',
    storageBucket: 'twende-nalo.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bGVo2anM_IlLt9dIcw2XG291KD7dxcA',
    appId: '1:248749012948:web:74d137d0e509586a5a0841',
    messagingSenderId: '248749012948',
    projectId: 'twende-nalo',
    authDomain: 'twende-nalo.firebaseapp.com',
    storageBucket: 'twende-nalo.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
